apiVersion: v2
appVersion: "1.16.0"
name: demo-app
description: A Helm chart deploying a microservice app
type: application
version: 0.1.0
dependencies:
  - name: mongodb
    condition: mongodb.enabled
    repository: https://github.com/sachin199112/rafay-helm/tree/main/demo-app/charts/mongodb
    version: 0.1.0
    import-values:
      - data
  - name: frontend
    condition: frontend.enabled
    repository: https://github.com/sachin199112/rafay-helm/tree/main/demo-app/charts/frontend
    version: "0.1.0"
  - name: nginxapp
    condition: nginxapp.enabled
    repository: https://github.com/sachin199112/rafay-helm/tree/main/demo-app/charts/nginxapp
    version: "0.1.0"
