apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.servicename }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.targetports }}
      targetPort: {{ .Values.targetports }}