apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.appname }}
  namespace: default
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
        imagePullPolicy: Always
        name: {{ .Values.podname }}
        ports:
        - containerPort: {{ .Values.ports }}
          protocol: TCP
