apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
spec:
  selector:
    app: {{ .Values.appname }}
  type: {{ .Values.servicetype }}
  ports:
   -  protocol: TCP
      port: {{ .Values.ports }}
      targetPort: {{ .Values.ports }}